CREATE TABLE "form_submissions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text,
	"house_id" uuid,
	"tracking_id" text,
	"relation" text,
	"occasion" text,
	"region" text,
	"group_size" text,
	"duration" text,
	"start_time" text,
	"event_date" text,
	"venue_type" text,
	"full_address" text,
	"message" text,
	"source" text,
	"method" text,
	"enquiry_date" text,
	"ip_address" text,
	"country" text,
	"city" text,
	"user_agent" text,
	"gclid" text
);
--> statement-breakpoint
CREATE TABLE "houses" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"title" text NOT NULL,
	"slug" text NOT NULL,
	"postcode" text NOT NULL,
	"region" text,
	"location" text NOT NULL,
	"address" text,
	"raw_address" text,
	"verified_address" text,
	"google_place_id" text,
	"description" text,
	"content" text,
	"features" text[],
	"sleeps" text,
	"image_url" text,
	"photo_1_url" text,
	"photo_2_url" text,
	"photo_3_url" text,
	"website_url" text,
	"airbnb_url" text,
	"booking_com_url" text,
	"vrbo_url" text,
	"other_booking_url" text,
	"meta_title" text,
	"meta_description" text,
	"is_published" boolean DEFAULT true,
	"is_featured" boolean DEFAULT false,
	"address_verified" boolean DEFAULT false,
	"booking_links_found" boolean DEFAULT false,
	"photos_extracted" boolean DEFAULT false,
	"photos_stored_in_blob" boolean DEFAULT false,
	"content_generated" boolean DEFAULT false,
	"enrichment_complete" boolean DEFAULT false,
	"google_maps_url" text,
	"affiliate_link" text,
	"contact_email" text,
	"ben_visited_dates" text[],
	"has_affiliate_relationship" boolean DEFAULT false,
	"owner_approved" boolean DEFAULT false,
	"owner_contact_info" text,
	"owner_notes" text,
	CONSTRAINT "houses_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "form_submissions" ADD CONSTRAINT "form_submissions_house_id_houses_id_fk" FOREIGN KEY ("house_id") REFERENCES "public"."houses"("id") ON DELETE no action ON UPDATE no action;